apiVersion: v1
kind: Secret
metadata:
  name: myrag-secrets
  namespace: myrag
type: Opaque
stringData:
  OPENRAG_ADMIN_TOKEN: "CHANGE_ME"
  KEYCLOAK_CLIENT_SECRET: "CHANGE_ME"
  LEGIFRANCE_CLIENT_ID: ""
  LEGIFRANCE_CLIENT_SECRET: ""
