"""
Re-embed a whole Milvus collection with another embedding model
===============================================================
Deployment-specific operational tool, NOT a schema migration: it lives in
``scripts/`` on purpose. A numbered file under
``services/persistence/migrations/milvus/`` would become the default target of
the generic runner for every deployment, and a new schema-version stamp would
make ``MilvusVectorStore._check_schema_version`` refuse the collection. The
collection this tool produces keeps the *same* schema version as its source.

Why: the dense ``vector`` field has a fixed dimension and one collection holds
every partition, so moving from one embedder to another of a different width
(here ``bge-multilingual-gemma2``, 3584 → ``bge-m3``, 1024) means building a new
collection next to the live one and swapping the names.

It reuses the rebuild machinery of ``2.rebuild_text_analyzer.py`` (schema,
indexes, ``_id`` preservation through ``allow_insert_auto_id``, server-side
BM25 regeneration, name swap, release of the collection left aside). The one
difference: the dense vector is **recomputed from ``text``** — which is exactly
the string that was embedded at indexing time — instead of being copied.

Everything goes through one idempotent step, :func:`reconcile`, which makes the
target collection equal to the source (same ``_id`` set, same fields). That one
step is the initial build, the resume after an interruption, and the catch-up:

* ``build``     create the target if needed and reconcile. Read-only on the
                source, so it can run **while OpenRAG is serving**; re-run it
                as often as needed — rows already embedded are not embedded
                again.
* ``status``    show what a reconcile would do. Changes nothing.
* ``finalize``  OpenRAG must be **stopped**. Reconcile one last time, verify
                (source unchanged, nothing left to do, same counts per
                partition, target dimension, re-embedded sample matches),
                then swap the names. The old collection is kept as
                ``<collection>_gemma2_backup`` and released from memory.
* ``rollback``  swap the backup back. Point-in-time: rows indexed after the
                swap live only in the collection moved aside.

Configuration comes from the environment, never from the command line, so the
key cannot end up in a process listing or a shell history:

    REEMBED_BASE_URL   e.g. https://gateway.example/v1
    REEMBED_MODEL      e.g. bge-m3
    REEMBED_API_KEY    bearer token

Usage (inside the application container, as the application user):
    python /app/scripts/reembed_bge_m3.py build [--dry-run] [--max-rpm 120]
    python /app/scripts/reembed_bge_m3.py status
    python /app/scripts/reembed_bge_m3.py finalize [--dry-run]
    python /app/scripts/reembed_bge_m3.py rollback [--dry-run]
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import importlib.util
import json
import math
import os
import sys
import time
from collections import Counter
from collections.abc import Callable, Iterable, Iterator
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from types import ModuleType
from typing import Any

import httpx
from _bootstrap import ensure_openrag_source_path

ensure_openrag_source_path()

from core.utils.logging import get_logger  # noqa: E402

TARGET_DIM = 1024

REBUILD_SUFFIX = "_bge_m3_rebuild"
BACKUP_SUFFIX = "_gemma2_backup"
ROLLBACK_ASIDE_SUFFIX = "_bge_m3_rolled_back"

#: Marks a collection as built by this tool, so ``build`` never adopts — and
#: never writes into — a collection that merely happens to carry the name.
REEMBED_MODEL_PROPERTY = "openrag.reembed_model"

#: Never written back (``sparse`` is generated by Milvus) or never part of a
#: row's identity (``vector`` is the very thing being replaced).
_VECTOR_KEYS = frozenset({"vector", "sparse"})

#: Texts per embedding request.
EMBED_BATCH = 32

#: Rows per ``_id in [...]`` fetch / delete.
ID_BATCH = 500

#: Requests per minute the tool allows itself. The key is shared with the
#: running application (LLM, reranker): using the whole quota for a bulk job
#: would turn into 429s for users.
DEFAULT_MAX_RPM = 120

#: Cap on a single wait, whatever ``Retry-After`` says.
_MAX_WAIT_SECONDS = 300.0

_RETRYABLE_STATUS = frozenset({429, 500, 502, 503, 504})

#: Cosine under which a re-embedded sample row counts as not matching the
#: vector stored in the target. The same text through the same model lands at
#: 0.999+; a vector attached to the wrong row lands far below.
_SAMPLE_MIN_COSINE = 0.99

#: Exit codes. ``EXIT_REFUSED``: the tool stopped before changing anything that
#: matters — the live collection is as it was. ``EXIT_UNKNOWN_STATE``: something
#: unexpected broke; a wrapper must not restart the application on its own.
EXIT_REFUSED = 1
EXIT_UNKNOWN_STATE = 2

logger = get_logger()


class ReembedError(RuntimeError):
    """Raised for every condition that must stop the tool before it writes."""


# ---------------------------------------------------------------------------
# Rebuild helpers, shared with migration 2
# ---------------------------------------------------------------------------


def _load_rebuild_helpers() -> ModuleType:
    """Import ``2.rebuild_text_analyzer.py`` the way the migration runner does."""
    import services.persistence.migrations.milvus as milvus_migrations

    path = Path(milvus_migrations.__file__).resolve().parent / "2.rebuild_text_analyzer.py"
    spec = importlib.util.spec_from_file_location("milvus_migration_v2", path)
    if spec is None or spec.loader is None:
        raise ReembedError(f"Cannot load the rebuild helpers from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _with_vector_dim(desc: dict[str, Any], dim: int) -> dict[str, Any]:
    """The source description with only the ``vector`` dimension replaced."""
    out = copy.deepcopy(desc)
    for f in out.get("fields", []):
        if f["name"] == "vector":
            f.setdefault("params", {})["dim"] = dim
            return out
    raise ReembedError("Collection has no `vector` field — not an OpenRAG collection.")


def _scalar_output_fields(desc: dict[str, Any]) -> list[str]:
    """Every declared field but the vectors, plus the dynamic ones (``$meta``)."""
    return [f["name"] for f in desc.get("fields", []) if f["name"] not in _VECTOR_KEYS] + ["$meta"]


# ---------------------------------------------------------------------------
# Embedding client
# ---------------------------------------------------------------------------


class GatewayEmbedder:
    """Minimal OpenAI-compatible ``/embeddings`` client for a bulk job.

    Not the application's ``VLLMEmbedder``: that one ignores ``Retry-After``
    and sits behind a circuit breaker meant for interactive traffic.
    """

    def __init__(
        self,
        base_url: str,
        model: str,
        api_key: str,
        *,
        dim: int = TARGET_DIM,
        max_rpm: int = DEFAULT_MAX_RPM,
        max_attempts: int = 8,
        http: Any | None = None,
        sleep: Callable[[float], None] = time.sleep,
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        self._url = base_url.rstrip("/") + "/embeddings"
        self._model = model
        self._dim = dim
        self._min_interval = 60.0 / max_rpm if max_rpm > 0 else 0.0
        self._max_attempts = max_attempts
        self._http = http or httpx.Client(timeout=180.0, headers={"Authorization": f"Bearer {api_key}"})
        self._sleep = sleep
        self._clock = clock
        self._last_request: float | None = None
        self.requests = 0
        self.texts = 0

    def embed(self, texts: list[str]) -> list[list[float]]:
        """Embed ``texts``. One vector per text, in order, or an exception."""
        out: list[list[float]] = []
        for start in range(0, len(texts), EMBED_BATCH):
            out.extend(self._embed_batch(texts[start : start + EMBED_BATCH]))
        return out

    def _pace(self) -> None:
        if self._last_request is not None and self._min_interval:
            wait = self._min_interval - (self._clock() - self._last_request)
            if wait > 0:
                self._sleep(wait)
        self._last_request = self._clock()

    def _embed_batch(self, batch: list[str]) -> list[list[float]]:
        last = "no attempt made"
        for attempt in range(self._max_attempts):
            self._pace()
            self.requests += 1
            try:
                response = self._http.post(self._url, json={"model": self._model, "input": batch})
            except httpx.TransportError as exc:
                last = f"{type(exc).__name__}: {exc}"
                self._sleep(min(2.0**attempt, _MAX_WAIT_SECONDS))
                continue
            if response.status_code in _RETRYABLE_STATUS:
                last = f"HTTP {response.status_code}"
                wait = _retry_after_seconds(response.headers.get("Retry-After"), default=2.0**attempt)
                logger.warning(f"  embedding endpoint answered {last}; waiting {wait:.0f}s")
                self._sleep(wait)
                continue
            if response.status_code != 200:
                raise ReembedError(f"Embedding endpoint answered HTTP {response.status_code}: {response.text[:300]}")
            return self._vectors(response.json(), len(batch))
        raise ReembedError(f"Embedding endpoint still failing after {self._max_attempts} attempts ({last}).")

    def _vectors(self, body: dict[str, Any], expected: int) -> list[list[float]]:
        data = sorted(body.get("data", []), key=lambda d: d["index"])
        if len(data) != expected:
            raise ReembedError(f"Embedding endpoint returned {len(data)} vectors for {expected} texts.")
        vectors = [d["embedding"] for d in data]
        wrong = {len(v) for v in vectors} - {self._dim}
        if wrong:
            raise ReembedError(f"Embedding endpoint returned dimension(s) {sorted(wrong)}, expected {self._dim}.")
        self.texts += expected
        return vectors


def _retry_after_seconds(header: str | None, *, default: float) -> float:
    """Seconds to wait from a ``Retry-After`` header (delta-seconds form)."""
    try:
        wait = float(header) if header is not None else default
    except ValueError:
        wait = default
    return max(0.0, min(wait, _MAX_WAIT_SECONDS))


# ---------------------------------------------------------------------------
# Reconcile
# ---------------------------------------------------------------------------


def _digest(value: str) -> bytes:
    return hashlib.sha256(value.encode("utf-8")).digest()


def _normalise(value: Any) -> Any:
    return value.isoformat() if isinstance(value, datetime) else value


def _fingerprint(row: dict[str, Any]) -> bytes:
    """Identity of a row: every field but the vectors."""
    payload = {k: _normalise(v) for k, v in row.items() if k not in _VECTOR_KEYS}
    return _digest(json.dumps(payload, sort_keys=True, ensure_ascii=False, default=str))


@dataclass
class _Snapshot:
    """What one full scan of a collection retains: two hashes per row."""

    fingerprints: dict[int, bytes] = field(default_factory=dict)
    text_digests: dict[int, bytes] = field(default_factory=dict)
    per_partition: Counter = field(default_factory=Counter)


@dataclass
class Plan:
    """The difference between source and target, as three disjoint ``_id`` lists."""

    to_embed: list[int]  # missing from the target, or present with another text
    to_patch: list[int]  # same text, other fields changed — the new vector is kept
    to_delete: list[int]  # gone from the source
    stale: list[int]  # subset of to_embed already in the target, to remove first
    source: _Snapshot
    target: _Snapshot

    @property
    def empty(self) -> bool:
        return not (self.to_embed or self.to_patch or self.to_delete)

    def summary(self) -> str:
        return (
            f"source={len(self.source.fingerprints)} rows, target={len(self.target.fingerprints)} rows — "
            f"to embed: {len(self.to_embed)}, to patch: {len(self.to_patch)}, to delete: {len(self.to_delete)}"
        )


def _scan(client: Any, collection: str, fields: list[str], page: int) -> _Snapshot:
    snapshot = _Snapshot()
    client.load_collection(collection)
    iterator = client.query_iterator(collection_name=collection, filter="", batch_size=page, output_fields=fields)
    try:
        while True:
            batch = iterator.next()
            if not batch:
                break
            for raw in batch:
                row = dict(raw)
                rid = row["_id"]
                snapshot.fingerprints[rid] = _fingerprint(row)
                snapshot.text_digests[rid] = _digest(row.get("text") or "")
                snapshot.per_partition[row.get("partition")] += 1
    finally:
        iterator.close()
    return snapshot


def _plan(source: _Snapshot, target: _Snapshot) -> Plan:
    to_embed, to_patch, stale = [], [], []
    for rid, fingerprint in source.fingerprints.items():
        if rid not in target.fingerprints:
            to_embed.append(rid)
        elif source.text_digests[rid] != target.text_digests[rid]:
            to_embed.append(rid)
            stale.append(rid)
        elif fingerprint != target.fingerprints[rid]:
            to_patch.append(rid)
    to_delete = [rid for rid in target.fingerprints if rid not in source.fingerprints]
    return Plan(sorted(to_embed), sorted(to_patch), sorted(to_delete), sorted(stale), source, target)


def _batches(ids: list[int], size: int) -> Iterator[list[int]]:
    for start in range(0, len(ids), size):
        yield ids[start : start + size]


def _fetch(client: Any, collection: str, ids: list[int], fields: list[str]) -> dict[int, dict[str, Any]]:
    rows = client.query(collection_name=collection, filter=f"_id in {ids}", output_fields=fields)
    return {dict(r)["_id"]: dict(r) for r in rows}


def _delete(client: Any, collection: str, ids: Iterable[int]) -> None:
    for batch in _batches(list(ids), ID_BATCH):
        client.delete(collection_name=collection, filter=f"_id in {batch}")


def reconcile(
    client: Any,
    helpers: ModuleType,
    embedder: GatewayEmbedder | None,
    source: str,
    target: str | None,
    *,
    dry_run: bool = False,
) -> Plan:
    """Make ``target`` hold exactly the rows of ``source``, re-embedded.

    ``target=None`` plans against an empty target (nothing built yet). The
    source is only ever read.
    """
    desc = client.describe_collection(source)
    fields = _scalar_output_fields(desc)
    page = helpers._copy_batch_size(desc)

    source_snapshot = _scan(client, source, fields, page)
    target_snapshot = _scan(client, target, fields, page) if target else _Snapshot()
    plan = _plan(source_snapshot, target_snapshot)
    logger.info(f"Reconcile plan: {plan.summary()}")
    if dry_run or plan.empty:
        return plan
    if target is None or embedder is None:
        raise ReembedError("reconcile needs a target collection and an embedder to apply a plan.")

    _delete(client, target, plan.to_delete + plan.stale)

    done = 0
    for ids in _batches(plan.to_embed, min(ID_BATCH, page)):
        rows = _fetch(client, source, ids, fields)
        # A row deleted since the scan is simply gone: the next reconcile agrees.
        present = [rid for rid in ids if rid in rows]
        vectors = embedder.embed([rows[rid].get("text") or "" for rid in present])
        if len(vectors) != len(present):
            raise ReembedError(f"{len(vectors)} vectors for {len(present)} rows — refusing to insert.")
        payload = []
        for rid, vector in zip(present, vectors, strict=True):
            row = helpers._prepare_row(rows[rid])
            row["vector"] = vector
            payload.append(row)
        if payload:
            client.insert(collection_name=target, data=payload)
        done += len(payload)
        logger.info(f"  embedded {done}/{len(plan.to_embed)} rows ({embedder.requests} requests)")

    for ids in _batches(plan.to_patch, min(ID_BATCH, page)):
        rows = _fetch(client, source, ids, fields)
        vectors = _fetch(client, target, ids, ["_id", "vector"])
        payload = []
        for rid in ids:
            if rid in rows and rid in vectors:
                row = helpers._prepare_row(rows[rid])
                row["vector"] = vectors[rid]["vector"]
                payload.append(row)
        _delete(client, target, [row["_id"] for row in payload])
        if payload:
            client.insert(collection_name=target, data=payload)
    if plan.to_patch:
        logger.info(f"  patched {len(plan.to_patch)} rows (fields changed, text unchanged — vector kept)")

    client.flush(target)
    return plan


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def _names(collection: str) -> tuple[str, str, str]:
    return f"{collection}{REBUILD_SUFFIX}", f"{collection}{BACKUP_SUFFIX}", f"{collection}{ROLLBACK_ASIDE_SUFFIX}"


def _vector_dim(helpers: ModuleType, client: Any, collection: str) -> int:
    return helpers._vector_dim(client.describe_collection(collection))


def _check_is_ours(helpers: ModuleType, client: Any, target: str, model: str) -> None:
    desc = client.describe_collection(target)
    built_with = desc.get("properties", {}).get(REEMBED_MODEL_PROPERTY)
    dim = helpers._vector_dim(desc)
    if built_with != model or dim != TARGET_DIM:
        raise ReembedError(
            f"Collection '{target}' exists but was not built by this tool for '{model}' "
            f"(marker={built_with!r}, dim={dim}). Inspect it and drop it before retrying."
        )


def _allow_explicit_ids(helpers: ModuleType, client: Any, target: str) -> None:
    """(Re)open the target to rows that carry their own ``_id``. Idempotent.

    ``finalize`` closes it just before the swap; if the swap then fails, the
    next run must be able to insert its catch-up rows again.
    """
    client.alter_collection_properties(target, properties={helpers.ALLOW_INSERT_AUTO_ID: "true"})


def _create_target(helpers: ModuleType, client: Any, source: str, target: str, model: str) -> None:
    source_desc = client.describe_collection(source)
    target_shape = _with_vector_dim(source_desc, TARGET_DIM)
    client.create_collection(
        collection_name=target,
        schema=helpers._build_v2_schema(client, target_shape),
        consistency_level="Strong",
        index_params=helpers._build_v2_index_params(client, target_shape),
        enable_dynamic_field=True,
    )
    helpers._assert_no_field_loss(source_desc, client.describe_collection(target))
    client.alter_collection_properties(
        target, properties={helpers.ALLOW_INSERT_AUTO_ID: "true", REEMBED_MODEL_PROPERTY: model}
    )
    logger.info(f"Created '{target}' (dim={TARGET_DIM}, model marker '{model}').")


def build(
    client: Any,
    helpers: ModuleType,
    embedder: GatewayEmbedder | None,
    collection: str,
    model: str,
    *,
    dry_run: bool = False,
) -> Plan:
    target, backup, _ = _names(collection)
    if client.has_collection(backup):
        raise ReembedError(f"'{backup}' already exists — this collection was already swapped. Nothing to build.")
    exists = client.has_collection(target)
    if exists:
        _check_is_ours(helpers, client, target, model)
        if not dry_run:
            _allow_explicit_ids(helpers, client, target)
    elif not dry_run:
        _create_target(helpers, client, collection, target, model)
        exists = True
    plan = reconcile(client, helpers, embedder, collection, target if exists else None, dry_run=dry_run)
    if dry_run:
        logger.info("[DRY-RUN] No changes were made.")
    return plan


def _cosine(a: list[float], b: list[float]) -> float:
    norm = math.sqrt(sum(x * x for x in a)) * math.sqrt(sum(y * y for y in b))
    return sum(x * y for x, y in zip(a, b, strict=True)) / norm if norm else 0.0


def _verify_sample(client: Any, embedder: GatewayEmbedder, target: str, ids: list[int], size: int) -> None:
    """Re-embed a spread of rows and compare with what the target stores.

    Counts and fingerprints prove the right rows are there; only this proves
    each row carries *its own* vector rather than a neighbour's.
    """
    if size <= 0 or not ids:
        return
    step = max(1, len(ids) // size)
    sample = ids[::step][:size]
    rows = _fetch(client, target, sample, ["_id", "text", "vector"])
    ordered = [rid for rid in sample if rid in rows]
    fresh = embedder.embed([rows[rid].get("text") or "" for rid in ordered])
    worst = min((_cosine(rows[rid]["vector"], vec), rid) for rid, vec in zip(ordered, fresh, strict=True))
    logger.info(f"Sample check: {len(ordered)} rows re-embedded, lowest cosine {worst[0]:.4f} (_id {worst[1]}).")
    if worst[0] < _SAMPLE_MIN_COSINE:
        raise ReembedError(
            f"Row {worst[1]} of '{target}' does not match its own text (cosine {worst[0]:.4f}). "
            "The target collection is not trustworthy — do not swap."
        )


def _wait_for_indexes(
    client: Any, collection: str, *, timeout: float = 900.0, sleep: Callable[[float], None] = time.sleep
) -> None:
    """Best effort: let the index build catch up before the collection goes live."""
    waited = 0.0
    try:
        while waited < timeout:
            pending = sum(
                int(client.describe_index(collection, name).get("pending_index_rows", 0))
                for name in client.list_indexes(collection)
            )
            if pending == 0:
                return
            logger.info(f"  waiting for indexes on '{collection}': {pending} rows pending")
            sleep(10.0)
            waited += 10.0
        logger.warning(
            f"Indexes on '{collection}' still building after {timeout:.0f}s — searches stay correct, only slower."
        )
    except Exception as exc:  # noqa: BLE001 — never fail a verified rebuild over an index probe
        logger.warning(f"Could not check index progress on '{collection}' ({exc}).")


def finalize(
    client: Any,
    helpers: ModuleType,
    embedder: GatewayEmbedder | None,
    collection: str,
    model: str,
    *,
    dry_run: bool = False,
    sample_size: int = 32,
) -> None:
    target, backup, _ = _names(collection)
    if not client.has_collection(target):
        raise ReembedError(f"'{target}' does not exist — run `build` first.")
    if client.has_collection(backup):
        raise ReembedError(f"'{backup}' already exists — inspect and drop it before finalizing.")
    _check_is_ours(helpers, client, target, model)

    if dry_run:
        plan = reconcile(client, helpers, None, collection, target, dry_run=True)
        logger.info(f"[DRY-RUN] Would apply the plan above, verify, and swap '{target}' into '{collection}'.")
        logger.info(f"[DRY-RUN] Rows left to embed during the window: {len(plan.to_embed)}. No changes were made.")
        return
    if embedder is None:
        raise ReembedError("finalize needs an embedder.")

    _allow_explicit_ids(helpers, client, target)
    count_before = helpers._row_count(client, collection)
    reconcile(client, helpers, embedder, collection, target)
    check = reconcile(client, helpers, None, collection, target, dry_run=True)
    count_after = helpers._row_count(client, collection)
    target_count = helpers._row_count(client, target)

    if count_after != count_before:
        raise ReembedError(
            f"The source changed during finalize: {count_before} rows before, {count_after} after. "
            f"Something is still writing to '{collection}' — stop OpenRAG and run finalize again."
        )
    if not check.empty:
        raise ReembedError(
            f"Source and target still differ after the catch-up ({check.summary()}). Stop OpenRAG and retry."
        )
    if target_count != count_after:
        raise ReembedError(f"Row-count mismatch: source={count_after}, target={target_count}. Nothing was swapped.")
    if check.source.per_partition != check.target.per_partition:
        raise ReembedError("Per-partition row counts differ between source and target. Nothing was swapped.")
    if _vector_dim(helpers, client, target) != TARGET_DIM:
        raise ReembedError(f"'{target}' is not a {TARGET_DIM}-dimension collection. Nothing was swapped.")
    _verify_sample(client, embedder, target, sorted(check.target.fingerprints), sample_size)
    logger.info(
        f"Verified: {target_count} rows, {len(check.target.per_partition)} partitions, same _id set and fields."
    )

    _wait_for_indexes(client, target)
    # Same schema as the source, so the same version stamp: the application
    # refuses a collection whose stamp differs from the one its build expects.
    client.drop_collection_properties(target, property_keys=[helpers.ALLOW_INSERT_AUTO_ID])
    helpers._stamp_version(client, target, helpers._get_stored_version(client, collection))

    helpers._swap_collections(client, collection, target, backup)
    # Past this line the swap is done: nothing below may turn it into a
    # reported failure, or the caller would roll the embedder back under a
    # collection that has already changed width.
    helpers._release(client, backup)
    try:
        client.load_collection(collection)
    except Exception as exc:  # noqa: BLE001 — the application loads the collection itself at startup
        logger.warning(f"Could not load '{collection}' after the swap ({exc}); OpenRAG loads it on startup.")
    logger.info(
        f"Done. '{collection}' now holds {TARGET_DIM}-dimension '{model}' vectors.\n"
        f"  The previous collection is kept as '{backup}' — drop it once validated.\n"
        "  Switch the embedder (DB record AND environment) before starting OpenRAG."
    )


def rollback(client: Any, helpers: ModuleType, collection: str, *, dry_run: bool = False) -> None:
    _, backup, aside = _names(collection)
    if not client.has_collection(backup):
        raise ReembedError(f"No backup collection '{backup}' — nothing to roll back to.")
    if client.has_collection(aside):
        raise ReembedError(f"Collection '{aside}' already exists — inspect and drop it before rolling back.")
    logger.info(
        f"{'[DRY-RUN] ' if dry_run else ''}Rolling back:\n"
        f"  '{collection}' → '{aside}' (kept aside)\n"
        f"  '{backup}' → '{collection}' (restored)"
    )
    if dry_run:
        logger.info("[DRY-RUN] No changes were made.")
        return
    helpers._swap_collections(client, collection, backup, aside)
    helpers._release(client, aside)
    client.load_collection(collection)
    logger.warning(
        f"Rollback complete. Rows indexed after the swap remain only in '{aside}'. "
        "Switch the embedder back (DB record AND environment) before starting OpenRAG."
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _model_from_env() -> str:
    model = os.environ.get("REEMBED_MODEL")
    if not model:
        raise ReembedError("Missing environment variable: REEMBED_MODEL")
    return model


def _embedder_from_env(model: str, max_rpm: int) -> GatewayEmbedder:
    missing = [k for k in ("REEMBED_BASE_URL", "REEMBED_API_KEY") if not os.environ.get(k)]
    if missing:
        raise ReembedError(f"Missing environment variable(s): {', '.join(missing)}")
    return GatewayEmbedder(os.environ["REEMBED_BASE_URL"], model, os.environ["REEMBED_API_KEY"], max_rpm=max_rpm)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Re-embed a whole Milvus collection with another embedding model.")
    parser.add_argument("command", choices=["build", "status", "finalize", "rollback"])
    parser.add_argument("--dry-run", action="store_true", help="Inspect only, make no changes")
    parser.add_argument(
        "--max-rpm", type=int, default=DEFAULT_MAX_RPM, help="Embedding requests per minute (0 = unpaced)"
    )
    parser.add_argument("--sample", type=int, default=32, help="Rows re-embedded by finalize to verify the target")
    args = parser.parse_args(argv)

    from core.config import load_config
    from pymilvus import MilvusClient

    cfg = load_config()
    collection = cfg.vectordb.collection_name
    client = MilvusClient(uri=f"http://{cfg.vectordb.host}:{cfg.vectordb.port}")
    helpers = _load_rebuild_helpers()

    try:
        if args.command == "rollback":
            rollback(client, helpers, collection, dry_run=args.dry_run)
            return 0
        if not client.has_collection(collection):
            raise ReembedError(f"Collection '{collection}' does not exist.")
        model = _model_from_env()
        # Inspecting needs no key: only a run that embeds does.
        if args.command == "status" or args.dry_run:
            if args.command == "finalize":
                finalize(client, helpers, None, collection, model, dry_run=True)
            else:
                build(client, helpers, None, collection, model, dry_run=True)
            return 0
        embedder = _embedder_from_env(model, args.max_rpm)
        if args.command == "build":
            build(client, helpers, embedder, collection, model)
        else:
            finalize(client, helpers, embedder, collection, model, sample_size=args.sample)
    except ReembedError as exc:
        logger.error(str(exc))
        return EXIT_REFUSED
    except Exception as exc:  # noqa: BLE001 — the caller must tell "refused" from "state unknown"
        logger.exception(f"Unexpected failure: {exc}")
        logger.error(
            f"The state of '{collection}' is NOT known. Check that it still exists before starting OpenRAG: "
            "an application started without it creates an empty one under the same name."
        )
        return EXIT_UNKNOWN_STATE
    return 0


if __name__ == "__main__":
    sys.exit(main())
